Add 'router static vrf' resources
CiscoDevNet/terraform-provider-iosxr pull request #237
Opened 2024-03-11 11:40 UTC by shebang42

Add resources & data sources for:
- iosxr_router_static_vrf
- iosxr_router_static_vrf_ipv4_multicast
- iosxr_router_static_vrf_ipv4_unicast
- iosxr_router_static_vrf_ipv6_multicast
- iosxr_router_static_vrf_ipv6_unicast

Notes:
- Not sure if I interpreted `id: true` correctly.
- `make testacc` fails.  Also with the unmodified code base.  Same as:
  https://github.com/CiscoDevNet/terraform-provider-iosxr/pull/213#issuecomment-1829405429

2024-03-14 11:57 UTC, danischm requested changes

2024-03-14 11:58 UTC, danischm commented
Thanks a lot for your contribution!

2024-03-14 16:51 UTC, shebang42 commented on gen/definitions/router_static_vrf.yaml
> +name: Router Static VRF
You're correct.  I assumed I need to be explicit in the config.
Commit [9b1f1c1]

2024-03-14 16:51 UTC, shebang42 commented on gen/definitions/router_static_vrf_address_family_ipv4_multicast.yaml
> +    id: true
Commit [75be364]

2024-03-14 16:52 UTC, shebang42 commented
Note: In ~3 weeks, more PR's will follow for router_bgp.

2024-03-19 23:15 UTC, danischm requested changes
After removing the `router_static_vrf` definition, we need to remove the related examples and .go files in the internal/provider directory manually.

2024-03-21 20:15 UTC, danischm approved these changes

2024-03-21 20:16 UTC, merged